### ISSUE TITLE
the sell limit order is not excuted

### ISSUE THREAD

**Issue by truongtamgio** [iilunin/crypto-bot#11]
Hello,
I created sell limit order but it doesn't executed. There is nothing happened in my account although the price is reached and I enable trading mode in api Binance. So, what is problem ? Thank you !

I have 15k CMT in balance
```
{
  "trade": {
    "id": "A8964745-4C4F-CCF6-05E4-03B9F0FE86D2",
    "asset": "CMT",
    "symbol": "CMTBTC",
    "side": "SELL",
    "status": "ACTIVE",
    "exit": {
      "smart": false,
      "threshold": "0.40%",
      "targets": [
        {
          "price": "0.00000655",
          "vol": "2.00000000",
          "sl": "0.00000623"
        }
      ]
    }
  }
}
```

**Comment by iilunin** [comment]
@truongtamgio your order won't execute. Min notional for this trading pair is 0.001 BTC- which means you have to supply around 153 CMTs at the price 0.00000655.
