### ISSUE TITLE
No volume left to process order

### ISSUE THREAD

**Issue by honzasach** [iilunin/crypto-bot#19]
Hello,

I have an issue with trade submitted via Web UI. There is the Exit strategy defined in the trade, as well as the Stoploss strategy. But I see these warning messages in the docker log that there's no volume left to process the order. 

**user@server:~$ sudo docker logs -f cryptobot
...
Orders to be posted: []
2021-04-30 01:42:23,244[WARNING][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: No volume left to process order @ price 259
2021-04-30 01:42:23,245[WARNING][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: No volume left to process order @ price 284
2021-04-30 01:42:23,247[INFO][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: Orders to be posted: []
2021-04-30 01:42:24,243[WARNING][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: No volume left to process order @ price 259
2021-04-30 01:42:24,244[WARNING][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: No volume left to process order @ price 284
...**

But the volume is there, even the Web UI shows me the volume: [https://imgur.com/h6RAFEj](https://imgur.com/h6RAFEj)

This is the trade in the Web UI: [https://imgur.com/NmwliUE](https://imgur.com/NmwliUE)

This is how the trade file looks like when I searched for it: [https://imgur.com/M5UPk2V](https://imgur.com/M5UPk2V)

The other strange thing to me is why the trade file (ZECUSDT_1920EF65-16B3-99DA-0C60-456CB412F2B5.json) is in the location /var/lib/docker/volumes/92454e26cf378dd2916f6c42ce922e856720c7606a8b2e6148452e9a2d300fa3/_data/, when I launched the docker container with the following command:
**docker run -d --rm -p xxx.xxx.xxx.xxx:3000:3000 --name cryptobot \
-e "TZ=Europe/Prague" \
-e "KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
-e "SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
-e "API_USER=xxxxxxxxxxxx" \
-e "API_PASS=xxxxxxxxxxxxxxxxxxx" \
-v $(pwd)/Active:/usr/src/crypto-bot/trades_active \
-v $(pwd)/Completed:/usr/src/crypto-bot/trades_completed \
-v $(pwd)/Config:/usr/src/crypto-bot/config:ro \
iilunin/crypto-bot:stable**

Do you have any idea what can be wrong there?

Thank you very much.

**Comment by iilunin** [comment]
Yeah,  there was an issue with rounding to the minimal step defined by the exchange which 0 in the case of ZECUSDT. I'll have a fresh stable build in 6-8 with that fix.

In regards to volumes - 

-v $(pwd)/Active:/usr/src/crypto-bot/trades_active Should be -v $(pwd)/Active:/usr/src/crypto-bot/trades
there's no volume _trades_active_ defined in the dockerfile

**Comment by honzasach** [comment]
Hello,
thank you very much for such quick response. I tried to download the latest release and test the ZECUSDT trade again. Unfortunately now I cannot create this or any other trade at all. 
I changed the volumes parameters like you suggested, as I had it wrong. But now I am unable to create basically any trade. :(

This is my command to run the bot: [https://imgur.com/G6AuwYv](https://imgur.com/G6AuwYv)

No error in the docker logging (I use: **docker logs -f cryptobot**)... Could there possibly be an issue of access rights to the folders for trades? Is there any way how can I troubleshoot it?

**Comment by honzasach** [comment]
I also noticed that the volumes are somehow linking to my home directory, when I did a docker inspection on running container:

"HostConfig": {
            "Binds": [
                "/home/myusername/Active:/usr/src/trades",
                "/home/myusername/Completed:/usr/src/complete_trades",
                "/home/myusername/Config:/usr/src/configs:ro"
            ],

[https://imgur.com/6MyfSlM](https://imgur.com/6MyfSlM)

I believe this issue is still related to the volumes. However I don't know how to solve it..

**Comment by iilunin** [comment]
$(pwd) command prints the current working directory, which is in your case /home/myusername/. When you run 'docker run' command from the terminal it expands `$(pwd)/Active` into` /home/current_user/Active`, which is the default directory. If you want to map it to some other location on your computer, you can either specify the full path (like ~/Cryptocurency/Bot/ActiveTrades) or  use CD command before running docker (like `cd  ~/Cryptocurency/Bot/`), then your working directory will be changed. 

The whole idea of mapping volumes between docker and your host machine is that you can see/change files and they are persisted even if you upgrade bot to the newer version.

**Comment by honzasach** [comment]
Ok, understood. Thanks for the explanation.

I did another test and created the trade JSON file directly from a command line in Linux. I placed the JSON file in the "Active" directory and the bot loaded it. Now I can even see it in the Web UI. Also, now it is possible to edit it the Web UI. 
However, I am still not able to create any new trades via the Web UI.

Also, there is this new repeated error now in the docker log:
**2021-04-30 10:26:37,724[ERROR][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: APIError(code=-1013): Filter failure: LOT_SIZE
2021-04-30 10:26:38,457[INFO][PlaceOrderStrategy(ZECUSDT)|Binance WebSocket Thread]: Orders to be posted: [{'price': 284.0, 'volume': 0.66319125, 'side': 'SELL', 'target': <Bot.Target.ExitTarget object at 0x7f4b208737d0>}]**

This is the JSON trade file: [https://imgur.com/Lm2Ea3E](https://imgur.com/Lm2Ea3E)
Do you see anything wrong in there?

Thank you very much.

**Comment by iilunin** [comment]
Please pull the latest version of the bot, it has lot size issue fixed.

**Comment by honzasach** [comment]
Ok, I have pulled the latest version and the error with LOT_SIZE is gone. 👍 

Now I also finally understand the volumes so I did this adjustment in the command to run the bot via docker:
-v /home/jansach/myusername/Active:/usr/src/trades \
-v /home/jansach/myusername/Completed:/usr/src/complete_trades \
-v /home/jansach/myusername/Config:/usr/src/configs:ro \

And it works great. It even loaded the previous trade file, as well as the api.json file with Binance API keys.
I can also see that the bot created the (non-smart) exit order correctly, so it's great!

However the Web UI is still unable to create a new trade. Is there a way I can help to troubleshoot it? I even tried to put 777 permissions on the "Active" directory to eliminate possible access rights issue, but it didn't help.

**Comment by honzasach** [comment]
> Ok, that's good.
> 
> For the Web UI, in google chrome (or firefox) you can use Developer Tools feature. Navigate to Network tab to see what Web UI sends and receives from the bot https://monosnap.com/file/StyqNIcVWxz1y4R7ysCqJ2LW4vpGZH
> ideally, you should see something like this https://monosnap.com/file/xPDODJlQVeN0TlzzZccluczfoi38wa but if an error happened during creation, the summary will be reflected in the response.
> 
> Also, docker logs will help to identify if the error happened in the bot.

Hello, thanks for the advice. I tried it and the issue is same as mentioned in #21. When I replace the comma with dot in the Exit targets default threshold for smart feature, the trade is created via Web UI. So, this was why it wasn't working for me. 

Screenshot -> [https://imgur.com/tlLM4Fv](https://imgur.com/tlLM4Fv)

**Comment by honzasach** [comment]
The "No volume left" error, as well as the "LOT_SIZE" errors have been solved in the releases v0.0.55 and v0.0.57. Therefore I am closing this issue now. Thank you @iilunin
