### ISSUE TITLE
Trade is not created in the Web UI

### ISSUE THREAD

**Issue by honzasach** [iilunin/crypto-bot#20]
Hello,
I was able to submit one trade but the other one I cannot submit. Or in other words, I can enter all the needed fields and hit "Create" but nothing happens, the trade is not created and I receive no message in the Web UI.

This is the trade I am trying to create: [https://imgur.com/a/XZfqDeT](https://imgur.com/a/XZfqDeT)

In the docker log I see only those two rows when hitting the Create button:
**2021-04-30 02:01:43,703[INFO][werkzeug|Thread-5725]: 82.99.141.xxx - - [30/Apr/2021 02:01:43] "POST /api/v1/trade/0 HTTP/1.1" 500 -
2021-04-30 02:01:43,736[INFO][werkzeug|Thread-5726]: 82.99.141.xxx - - [30/Apr/2021 02:01:43] "GET /api/v1/trades HTTP/1.1" 200 -**

But as I wrote, I don't see the trade in the list of trades and I don't receive any error message in the Web UI. Sincerely I don't know what is wrong with it.

The only difference between the trade that was created and the one that wasn't created, is that the one that was created was without decimal point, there I used only integers. But the one that wasn't created, I needed to enter 7 or 8 decimal positions, but I suppose this shouldn't be an issue, right?

Thanks in advance for your support.

**Comment by iilunin** [comment]
It's related to issue #19  where you incorrectly define volume mapping for active trades for the docker.

**Comment by honzasach** [comment]
Actually it is related to #21
