### ISSUE TITLE
Threshold default value 0,4% (es_ES locale)

### ISSUE THREAD

**Issue by oscar-ol** [iilunin/crypto-bot#21]
Trade is not created if I use default value for threshold in Exit Targets -> Default Settings.

Default value 0.4% in spanish locale is converted to 0,4% and it is not valid.

"{\"status\": 100, \"msg\": \"could not convert string to float: '0,4'\"}"

Thank you.

**Comment by iilunin** [comment]
can you try using dot instead of coma? 0,4 -> 0.4? 
I'll fix this in the version.

**Comment by oscar-ol** [comment]
Yes, it works if I replace 0,4 to 0.4.
I think you can remove toLocalString() in trade-details.ts
      `this.threshold = 0.4.toLocaleString() + '%';`
Thank you!
