### ISSUE TITLE
Stoploss not triggered

### ISSUE THREAD

**Issue by pascal00d** [iilunin/crypto-bot#23]
Hello,

Today I had a trade with TRUUSDT, with a stop loss at 0.29800000, and when the price price fallen closer to this stop-loss value nothing happenned. Nothing more when the price price hited this stop-loss value (18h03 UTC+2).
I don't see any action or error in the logs
Did I miss something or this is an issue ?

    "stoploss": {
      "type": "TRAILING",
      "threshold": "10%",
      "initial_target": {
        "price": "0.29800000",
        "vol": "100%"
      }
    }

[TRUUSDT_291860A3-B9CA-F6C2-94D3-2163A49E4EAF.txt](https://github.com/iilunin/crypto-bot/files/6517580/TRUUSDT_291860A3-B9CA-F6C2-94D3-2163A49E4EAF.txt)
[TRUUSDT.txt](https://github.com/iilunin/crypto-bot/files/6517581/TRUUSDT.txt)

**Comment by iilunin** [comment]
Hello,

That's correct behavior. 

Trailing stop loss activates only after at least one target is completed. 

https://github.com/iilunin/crypto-bot/blob/master/Docs/FLOW.md#stop-loss

**Comment by iilunin** [comment]
You're right. There is a mistake in this example. Trailing stop loss won't be activated by default unless at least one target is completed. I'll update this document.
